apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-service.fullname" . }}-inference
  labels:
    {{- include "ml-service.labels" . | nindent 4 }}
    component: inference
  {{- with .Values.inference.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.inference.service.type }}
  ports:
    - port: {{ .Values.inference.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ml-service.selectorLabels" . | nindent 4 }}
    component: inference

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-service.fullname" . }}-training
  labels:
    {{- include "ml-service.labels" . | nindent 4 }}
    component: training
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ml-service.selectorLabels" . | nindent 4 }}
    component: training
